# Generated by Django 4.2.7 on 2023-11-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencymodel',
            name='purchaseRate',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='currencymodel',
            name='saleRate',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
    ]
