# Generated by Django 4.2.7 on 2023-11-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_alter_currencymodel_purchaserate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencymodel',
            name='purchaseRate',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currencymodel',
            name='purchaseRateNB',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='currencymodel',
            name='saleRate',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currencymodel',
            name='saleRateNB',
            field=models.BigIntegerField(),
        ),
    ]
