# Generated by Django 4.2.7 on 2023-11-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_alter_currencymodel_purchaserate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencymodel',
            name='purchaseRate',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='currencymodel',
            name='saleRate',
            field=models.BigIntegerField(null=True),
        ),
    ]
