# Generated by Django 4.2.7 on 2023-11-11 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshops', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='phone',
            field=models.CharField(max_length=18, validators=[django.core.validators.RegexValidator('^\\+?3?8?(0[\\s\\.-]\\d{2}[\\s\\.-]\\d{3}[\\s\\.-]\\d{2}[\\s\\.-]\\d{2})$', ['Only ukrainian numbers allowed', 'Example: +380 50 672 25 61'])]),
        ),
    ]
