# Generated by Django 4.2.7 on 2023-11-11 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z\\D]{1,20}$', 'Brand first letter must be uppercase,  min 2 max 30 characters, no digits')])),
                ('model', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z\\d]{1,20}$', 'Model first letter must be uppercase,  min 1 max 30 characters, digits allowed')])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2023)])),
                ('city', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(999999999)])),
                ('currency', models.CharField(choices=[('USD', 'Usd'), ('UAH', 'Uah'), ('EUR', 'Eur')], max_length=3)),
                ('body', models.CharField(choices=[('Jeep', 'Jeep'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('SUV', 'Suv'), ('Coupe', 'Coupe'), ('Van', 'Van'), ('Minivan', 'Minivan'), ('Convertible', 'Convertible'), ('Roadster', 'Roadster'), ('Muscle car', 'Muscle Car')], max_length=11)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
