# Generated by Django 4.2.7 on 2023-11-10 14:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarShopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('[A-ZА-ЯЇІЄҐ][ А-Яа-яa-zA-ZЇїІіЄєҐґ\\d]{2,20}$Name first letter must be uppercase,  min 2 max 30 characters')])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'carshops',
            },
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Sale', 'Sale'), ('Mechanic', 'Mechanic')], max_length=8)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=13)),
                ('carshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='carshops.carshopmodel')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
    ]
