# Generated by Django 4.2.7 on 2023-11-10 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carshopmodel',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-ZА-ЯЇІЄҐ][ А-Яа-яa-zA-ZЇїІіЄєҐґ\\d]{2,20}$', 'Name first letter must be uppercase,  min 2 max 30 characters')]),
        ),
    ]
