# Generated by Django 4.2.7 on 2023-11-10 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carshops', '0002_alter_carshopmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshopmodel',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='carshop', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
