# Generated by Django 4.2.7 on 2023-11-10 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z\\D]{1,20}$', 'Brand first letter must be uppercase,  min 2 max 30 characters, no digits')]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='model',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z\\d]{0,20}$', 'Model first letter must be uppercase,  min 1 max 30 characters, digits allowed')]),
        ),
    ]
