# Generated by Django 4.2.7 on 2023-11-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='carshop',
        ),
    ]
