# Generated by Django 4.2.7 on 2023-11-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usermodel_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_carshop',
            field=models.BooleanField(default=False),
        ),
    ]
